package com.example.demo.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import lombok.Data;


@Entity
@Table(name = "users")
@Data
public class User {
  // ==============
  // PRIVATE FIELDS
  // ==============
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  // The user email
  @NotNull
  private String email;
  // The user name
  @NotNull
  private String name;
  // ==============
  // PUBLIC METHODS
  // ==============
  public User() { }
  public User(long id) {
    this.id = id;
  }
  // Getter and setter methods
  // ...
} // class User